# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTQb7PbCMPsNgbeh84Ke2JtZq-LelkPT
"""

n = int ( input ( "Ingrese numero: " ) )
sum = n * ( n + 1 ) / 2 
print ( int ( sum )  ) ;

