# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PgmAQLmiah_PyS1QdRv5TlaYTHczuX_i
"""

n = int ( input ( "Ingrese numero: " ) ) 
sum = 0 
for i in range ( 1 , n + 1 ): 
  sum += i 
print ( sum )



